/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/notFound'
import { Route as IndexImport } from './routes/index'
import { Route as LeaguesLeagueSlugSchedulesImport } from './routes/leagues/$leagueSlug/schedules'
import { Route as LeaguesLeagueSlugHomeImport } from './routes/leagues/$leagueSlug/home'
import { Route as LeaguesLeagueSlugLayoutImport } from './routes/leagues/$leagueSlug/_layout'
import { Route as LeaguesLeagueSlugGameDetailsScheduleIdImport } from './routes/leagues/$leagueSlug/gameDetails/$scheduleId'

// Create Virtual Routes

const LeaguesLeagueSlugImport = createFileRoute('/leagues/$leagueSlug')()

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  path: '/notFound',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeagueSlugRoute = LeaguesLeagueSlugImport.update({
  path: '/leagues/$leagueSlug',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeagueSlugSchedulesRoute = LeaguesLeagueSlugSchedulesImport.update(
  {
    path: '/schedules',
    getParentRoute: () => LeaguesLeagueSlugRoute,
  } as any,
)

const LeaguesLeagueSlugHomeRoute = LeaguesLeagueSlugHomeImport.update({
  path: '/home',
  getParentRoute: () => LeaguesLeagueSlugRoute,
} as any)

const LeaguesLeagueSlugLayoutRoute = LeaguesLeagueSlugLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LeaguesLeagueSlugRoute,
} as any)

const LeaguesLeagueSlugGameDetailsScheduleIdRoute =
  LeaguesLeagueSlugGameDetailsScheduleIdImport.update({
    path: '/gameDetails/$scheduleId',
    getParentRoute: () => LeaguesLeagueSlugRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/notFound': {
      id: '/notFound'
      path: '/notFound'
      fullPath: '/notFound'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueSlug': {
      id: '/leagues/$leagueSlug'
      path: '/leagues/$leagueSlug'
      fullPath: '/leagues/$leagueSlug'
      preLoaderRoute: typeof LeaguesLeagueSlugImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueSlug/_layout': {
      id: '/leagues/$leagueSlug/_layout'
      path: '/leagues/$leagueSlug'
      fullPath: '/leagues/$leagueSlug'
      preLoaderRoute: typeof LeaguesLeagueSlugLayoutImport
      parentRoute: typeof LeaguesLeagueSlugRoute
    }
    '/leagues/$leagueSlug/home': {
      id: '/leagues/$leagueSlug/home'
      path: '/home'
      fullPath: '/leagues/$leagueSlug/home'
      preLoaderRoute: typeof LeaguesLeagueSlugHomeImport
      parentRoute: typeof LeaguesLeagueSlugImport
    }
    '/leagues/$leagueSlug/schedules': {
      id: '/leagues/$leagueSlug/schedules'
      path: '/schedules'
      fullPath: '/leagues/$leagueSlug/schedules'
      preLoaderRoute: typeof LeaguesLeagueSlugSchedulesImport
      parentRoute: typeof LeaguesLeagueSlugImport
    }
    '/leagues/$leagueSlug/gameDetails/$scheduleId': {
      id: '/leagues/$leagueSlug/gameDetails/$scheduleId'
      path: '/gameDetails/$scheduleId'
      fullPath: '/leagues/$leagueSlug/gameDetails/$scheduleId'
      preLoaderRoute: typeof LeaguesLeagueSlugGameDetailsScheduleIdImport
      parentRoute: typeof LeaguesLeagueSlugImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  NotFoundRoute,
  LeaguesLeagueSlugRoute: LeaguesLeagueSlugRoute.addChildren({
    LeaguesLeagueSlugHomeRoute,
    LeaguesLeagueSlugSchedulesRoute,
    LeaguesLeagueSlugGameDetailsScheduleIdRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notFound",
        "/leagues/$leagueSlug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/notFound": {
      "filePath": "notFound.tsx"
    },
    "/leagues/$leagueSlug": {
      "filePath": "leagues/$leagueSlug",
      "children": [
        "/leagues/$leagueSlug/_layout",
        "/leagues/$leagueSlug/home",
        "/leagues/$leagueSlug/schedules",
        "/leagues/$leagueSlug/gameDetails/$scheduleId"
      ]
    },
    "/leagues/$leagueSlug/_layout": {
      "filePath": "leagues/$leagueSlug/_layout.tsx",
      "parent": "/leagues/$leagueSlug"
    },
    "/leagues/$leagueSlug/home": {
      "filePath": "leagues/$leagueSlug/home.tsx",
      "parent": "/leagues/$leagueSlug"
    },
    "/leagues/$leagueSlug/schedules": {
      "filePath": "leagues/$leagueSlug/schedules.tsx",
      "parent": "/leagues/$leagueSlug"
    },
    "/leagues/$leagueSlug/gameDetails/$scheduleId": {
      "filePath": "leagues/$leagueSlug/gameDetails/$scheduleId.tsx",
      "parent": "/leagues/$leagueSlug"
    }
  }
}
ROUTE_MANIFEST_END */
