/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LeaguesLeagueSlugSchedulesImport } from './routes/leagues/$leagueSlug/schedules'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeagueSlugSchedulesRoute = LeaguesLeagueSlugSchedulesImport.update(
  {
    path: '/leagues/$leagueSlug/schedules',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueSlug/schedules': {
      id: '/leagues/$leagueSlug/schedules'
      path: '/leagues/$leagueSlug/schedules'
      fullPath: '/leagues/$leagueSlug/schedules'
      preLoaderRoute: typeof LeaguesLeagueSlugSchedulesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LeaguesLeagueSlugSchedulesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/leagues/$leagueSlug/schedules"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/leagues/$leagueSlug/schedules": {
      "filePath": "leagues/$leagueSlug/schedules.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
